spring.application.name=api-gateway

server.port=8080

# Employee API Route
spring.cloud.gateway.routes[0].id=employee-service
spring.cloud.gateway.routes[0].uri=lb://employee-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/employee/api/v1/users/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Employee Swagger Route
spring.cloud.gateway.routes[1].id=employee-swagger
spring.cloud.gateway.routes[1].uri=lb://employee-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/employee/v3/api-docs,/employee/swagger-ui/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

